name = "go-auth-website"
main = "dist/worker.js"
compatibility_date = "2025-05-03"

[build]
command = "bun run build"
upload_format = "modules"

[[d1_databases]]
binding = "DB"
database_name = "go-auth-website"
database_id = "ef2719c9-959a-42f2-83d4-46d318f0bf61"

[[kv_namespaces]]
binding = "AUTH_KV"
id = "36f4562fa8e14a92b81aa627279f6d74"

[vars]
# SESSION_SECRET is stored as a secret